// Code generated by MockGen. DO NOT EDIT.
// Source: test/controllers (interfaces: Iuser)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
)

// MockIuser is a mock of Iuser interface.
type MockIuser struct {
	ctrl     *gomock.Controller
	recorder *MockIuserMockRecorder
}

// MockIuserMockRecorder is the mock recorder for MockIuser.
type MockIuserMockRecorder struct {
	mock *MockIuser
}

// NewMockIuser creates a new mock instance.
func NewMockIuser(ctrl *gomock.Controller) *MockIuser {
	mock := &MockIuser{ctrl: ctrl}
	mock.recorder = &MockIuserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIuser) EXPECT() *MockIuserMockRecorder {
	return m.recorder
}

// AllUsers mocks base method.
func (m *MockIuser) AllUsers(arg0 *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AllUsers", arg0)
}

// AllUsers indicates an expected call of AllUsers.
func (mr *MockIuserMockRecorder) AllUsers(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllUsers", reflect.TypeOf((*MockIuser)(nil).AllUsers), arg0)
}
